/*
 * Project: react-boilerplate
 * Author: Duong Le (navi.ocean@outlook.com)
 * File Created: Sunday, 1st April 2018 8:21:22 pm
 * Last Modified: Monday, 13th August 2018 5:23:16 pm
 */
export const RESET = 'RESET';
// Preloader
export const SHOW_PRELOADER = 'SHOW_PRELOADER';
export const HIDE_PRELOADER = 'HIDE_PRELOADER';
// Home
export const FETCH_HOME = 'FETCH_HOME';
export const FETCH_HOME_SUCCESS = 'FETCH_HOME_SUCCESS';
export const FETCH_HOME_FAILED = 'FETCH_HOME_FAILED';
// seo
export const SET_TITLE = 'SET_TITLE';
export const SET_DESC = 'SET_DESC';
export const SET_OG = 'SET_OG';
// Page
export const FETCH_PAGE = 'FETCH_PAGE';
export const FETCH_PAGE_SUCCESS = 'FETCH_PAGE_SUCCESS';
export const FETCH_PAGE_FAILED = 'FETCH_PAGE_FAILED';
// Subscribe
export const SEND_SUBSCRIBE = 'SEND_SUBSCRIBE';

// Alert
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

// Loading
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

// Contact
export const FETCH_CONTACT = 'FETCH_CONTACT';
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';
export const FETCH_CONTACT_FAILED = 'FETCH_CONTACT_FAILED';
export const FETCH_CONTACT_INPROCESS = 'FETCH_CONTACT_INPROCESS';
export const SEND_CONTACT = 'SEND_CONTACT';

// Auth
export const SUBMIT_LOGIN = 'SUBMIT_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SUBMIT_FORGOT = 'SUBMIT_FORGOT';
export const SUBMIT_SIGNUP = 'SUBMIT_SIGNUP';
export const SUBMIT_RESET = 'SUBMIT_RESET';
export const SUBMIT_VERIFY = 'SUBMIT_VERIFY';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';

export const SUBMIT_VERIFICATION_CODE = 'SUBMIT_VERIFICATION_CODE';
export const RESEND_CODE = 'RESEND_CODE';

// User
export const FETCH_USER = 'FETCH_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const SUBMIT_USER_INFO = 'SUBMIT_USER_INFO';
export const SUBMIT_USER_PHOTO = 'SUBMIT_USER_PHOTO';
export const FETCH_KEYPAIR = 'FETCH_KEYPAIR';
export const SET_KEYPAIR = 'SET_KEYPAIR';
export const FETCH_USER_STATUS = 'FETCH_USER_STATUS';
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS';
export const SET_REFERRAL = 'SET_REFERRAL';
// wallet
export const FETCH_WALLET = 'FETCH_WALLET';
export const SET_WALLET = 'SET_WALLET';

// dashboard
export const FETCH_DASHBOARD = 'FETCH_DASHBOARD';
export const SET_DASHBOARD = 'SET_DASHBOARD';

// Setting
export const SET_SETTINGS = 'SET_SETTINGS';

export const FETCH_SETTINGS = 'FETCH_SETTINGS';

// Buy Token
export const TOGGLE_BUY_TOKEN = 'TOGGLE_BUY_TOKEN';
export const FETCH_RATE = 'FETCH_RATE';
export const FETCH_RATE_SUCCESS = 'FETCH_RATE_SUCCESS';
export const FETCH_RATE_FAILED = 'FETCH_RATE_FAILED';

// Account
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAILED = 'ADD_ADDRESS_FAILED';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const TOGGLE_ADD_ADDRESS = 'TOGGLE_ADD_ADDRESS';

// Transaction
export const SUBMIT_TRANSACTION = 'SUBMIT_TRANSACTION';
export const CONFIRM_TRANSACTION = 'CONFIRM_TRANSACTION';
export const SET_TRANSACTION = 'SET_TRANSACTION';
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';

// Airdrop
export const FETCH_AIRDROP = 'FETCH_AIRDROP';
export const SET_AIRDROP = 'SET_AIRDROP';
export const SUBMIT_INVITE_EMAIL = 'SUBMIT_INVITE_EMAIL';
export const SUBMIT_FOLLOW_TWITTER = 'SUBMIT_FOLLOW_TWITTER';
export const SUBMIT_FOLLOW_TELEGRAM = 'SUBMIT_FOLLOW_TELEGRAM';
export const UPDATE_FOLLOW = 'UPDATE_FOLLOW';
export const JOIN_PROMOTE_TWITTER = 'JOIN_PROMOTE_TWITTER';
export const ADD_LINK_PROMOTE_TWITTER = 'ADD_LINK_PROMOTE_TWITTER';
export const JOIN_PROMOTE_BITCOINTALK = 'JOIN_PROMOTE_BITCOINTALK';
export const ADD_LINK_PROMOTE_BITCOINTALK = 'ADD_LINK_PROMOTE_BITCOINTALK';
export const UPDATE_PROMOTE = 'UPDATE_PROMOTE';
export const JOIN_CREATED = 'JOIN_CREATED';
export const UPDATE_CREATED = 'UPDATE_CREATED';
